replicaCount: 2

image:
  repository: temibabs/babs
  tag: staging
  pullPolicy: Always
  pullSecrets: regcred

service:
  name: babs-service
  type: ClusterIP
  externalPort: 80
  internalPort: 5000

ingress:
  enabled: true
  hosts:
    - host: api.babs.ai
      paths:
        - "/"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    ingress.kubernetes.io/secure-backends: "true"
  tls: []

resources: {}

envs:
  - name: LOG_LEVEL
    value: error
  - name: BABS_APP_VERSION
    value: 0
  - name: DB_HOST
    value: "lin-11195-2961-pgsql-primary.servers.linodedb.net"
  - name: DB_PASS
    value: "bEV4k8sct#UP5FvZ"
  - name: DB_PORT
    value: "5432"
  - name: DB_SCHEME
    value: postgresql
  - name: DB_USER
    value: linpostgres
  - name: DB_NAME
    value: babs
  - name: FLASK_CONFIG
    value: test
  - name: TWILIO_WA_PHONE_NUMBER
    value: +14155238886
  - name: TWILIO_SID
    value: AC15d2e71dbdc0d9289158abe54d6c2ad3
  - name: TWILIO_TOKEN
    value: bd283e728d36ff5f34ec776b9116b9c5