apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    app: {{ include "k8s.name" . }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8s.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "k8s.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: babs-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.envs }}
            - name: {{ .name }}
              value: {{ .value }}
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .alias }}
                       {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | indent 8 }}
      {{- end }}
