name: Build & Deploy

on:
  push:
    branches:
      - staging

env:
  AWS_REGION: eu-west-2
  REPOSITORY: temibabs/babs
  ECS_SERVICE: babs-app
  ECS_CLUSTER: babs-staging
  ECS_TASK_DEFINITION: task-definition.json
  CONTAINER_NAME: babs-app

permissions:
  contents: read

jobs:
  build:
    name: Build and push to Dockerhub
    runs-on: ubuntu-latest
    environment: staging

    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REPOSITORY }}

    - name: Build, tag, and push image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - run: echo ${{ steps.build-image.outputs.image }}

  deploy:
    name: Deploy to Linode
    runs-on: ubuntu-latest
    environment: staging
    needs: build

    steps:
    - name: Checkout staging
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        echo "Deploying to Linode"
        apt-get update && apt-get install -y helm kubectl
        export KUBECONFIG=./staging-kubeconfig.yml
        helm upgrade --install babs-web ./k8s --namespace babs --values ./k8s/staging-values.yml --set image.tag=${{ needs.build.outputs.image }}
